/**
 * Détection des fichiers générés (sorties de build, bundles, minifiés).
 *
 * Analyser ces fichiers ne produit que du bruit : ce n'est pas du code qu'on
 * édite, les motifs y sont ceux du bundler, et un même problème y apparaît
 * autant de fois qu'il y a de chunks. Module pur, donc testable.
 */

/** Segments de chemin qui signalent une sortie de build, même hors excludeFolders. */
const GENERATED_DIR =
  /(^|[\\/])(\.next|\.nuxt|\.svelte-kit|\.astro|\.output|\.turbo|\.cache|\.parcel-cache|\.vercel|\.netlify|dist|build|coverage|__pycache__|\.mypy_cache|\.pytest_cache|node_modules|bower_components|generated|__generated__|migrations)([\\/]|$)/i;

/** Noms de fichiers typiques d'un artefact de build. */
const GENERATED_FILE =
  /(\.min\.(js|css)|\.bundle\.js|\.chunk\.js|\.map|\.lock|-lock\.json)$|(^|[\\/])[\w.-]+\.[0-9a-f]{8,}\.(js|css|mjs)$/i;

/** Ligne au-delà de laquelle on considère le fichier comme minifié. */
const MINIFIED_LINE = 5000;
/** Longueur moyenne de ligne au-delà de laquelle le fichier n'est plus écrit à la main. */
const MINIFIED_AVERAGE = 500;

/** Le chemin indique-t-il un fichier généré ? */
export function isGeneratedPath(fsPath: string): boolean {
  return GENERATED_DIR.test(fsPath) || GENERATED_FILE.test(fsPath);
}

/**
 * Le contenu ressemble-t-il à du code minifié ou bundlé ?
 * Complète la détection par chemin : un bundle peut être écrit n'importe où.
 */
export function looksMinified(text: string): boolean {
  if (!text) return false;

  const lines = text.split(/\r?\n/);
  // Une seule ligne interminable : signature du minifié.
  if (lines.some((l) => l.length > MINIFIED_LINE)) return true;

  // Peu de lignes très longues : bundle non minifié mais généré.
  const meaningful = lines.filter((l) => l.trim().length > 0);
  if (meaningful.length < 3) return false;
  const average = meaningful.reduce((sum, l) => sum + l.length, 0) / meaningful.length;
  return average > MINIFIED_AVERAGE;
}

/** Bandeau `@generated` / `eslint-disable` posé par les générateurs de code. */
const GENERATED_BANNER = /^[\s/*#-]*(@generated|Code generated by|DO NOT EDIT|autogenerated)/im;

export function hasGeneratedBanner(text: string): boolean {
  // On ne regarde que l'en-tête : le bandeau y est toujours.
  return GENERATED_BANNER.test(text.slice(0, 500));
}

/** Faut-il analyser ce fichier ? */
export function shouldSkipGenerated(fsPath: string, text: string): boolean {
  return isGeneratedPath(fsPath) || hasGeneratedBanner(text) || looksMinified(text);
}
